# Generated by Django 5.0.6 on 2024-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_pizza_delete_pizaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consist', models.TextField()),
                ('prise', models.IntegerField()),
                ('is_spicy', models.BooleanField()),
            ],
        ),
    ]
