# Generated by Django 5.0.6 on 2024-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_burger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('is_alcacol', models.BooleanField()),
                ('volume', models.IntegerField()),
                ('consit', models.TextField()),
            ],
        ),
    ]
