# Generated by Django 5.0.6 on 2024-06-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='volume',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='consit',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='is_alcacol',
        ),
    ]
